### ISSUE TITLE
 Avalonia-CustomTitleBarTemplate not working Avalonia 11.0.0 RC1

### ISSUE THREAD

**Issue by henrrymoraes83** [FrankenApps/Avalonia-CustomTitleBarTemplate#10]
I'm trying build the Avalonia-CustomTitleBarTemplate with Avalonia 11.0.0 RC1 but this it not working.

There are 5 erros on Build:

![image](https://github.com/FrankenApps/Avalonia-CustomTitleBarTemplate/assets/135464720/e84d9066-4689-4177-a884-159390b35f46)

Do you know to fix it?

**Comment by henrrymoraes83** [comment]
After solve the problem above using partcial class. About the theme,  it was necessary hard code the fix the theme issue because on avalonia 11 themes is not supported  using the same method then implemented here.

**Comment by FrankenApps** [comment]
Basic support for Avalonia v.0.11 is now present.
