### ISSUE TITLE
How to customize the title bar in Linux

### ISSUE THREAD

**Issue by TDJK-DMRF** [FrankenApps/Avalonia-CustomTitleBarTemplate#5]
How to customize the title bar in Linux

**Comment by FrankenApps** [comment]
You would have to remove [this](https://github.com/FrankenApps/Avalonia-CustomTitleBarTemplate/blob/47fc0a5adb3fd8515bcd588f47e7d1703eeeb638/Views/MainWindow.axaml.cs#L31) and then implement it the same way as its done for windows and macos.

The reason I did not include this, is that there are so many linux distros where the title bar looks different, so you would take away the option to customize the title bar from your users...
