### ISSUE TITLE
Couple issues

### ISSUE THREAD

**Issue by derekantrican** [FrankenApps/Avalonia-CustomTitleBarTemplate#7]
First, should `MacosTitleBar` here be `WindowsTitleBar`?

https://github.com/FrankenApps/Avalonia-CustomTitleBarTemplate/blob/47fc0a5adb3fd8515bcd588f47e7d1703eeeb638/Views/CustomTitleBars/WindowsTitleBar.axaml.cs#L31-L32

Second, this library doesn't seem to be compatible with newer versions of Avalonia (namely: looks like this library is using 0.10.0 and I'm on 0.10.13) as the signature of `IObservable.Subscribe` has changed. I would love to use the examples you've written, but don't have the time to fix the breaking changes. (It's probably a quick fix, but currently don't have the time to look into it).

Thanks for making this library! It looks great and I look forward to using it

**Comment by FrankenApps** [comment]
You are right, `MacosTitleBar` should have been `WindowsTitleBar` there. I haven't used (or updated) this in a while so I went ahead and just did this (+ fixed this issue).

However I am not able to reproduce your Issue regarding the changed signature of `IObservable.Subscribe`. For me the Code still compiles and runs fine on (now) .net6. Did you check out the repo and ran it, or did you implement this on your own?

**Comment by derekantrican** [comment]
Are you saying you upgraded the .NET version or the Avalonia version? It sounds like you upgraded the .NET version since you mentioned .NET 6. But I am referring to the version of the Avalonia package.

**Comment by FrankenApps** [comment]
I upgraded both. AvaloniaUI is now on the latest Version (0.10.15).

**Comment by derekantrican** [comment]
Ah, looking at your commit perhaps I was missing an Avalonia package. I'll try again tonight

**Comment by derekantrican** [comment]
Actually I was able to fix it. There was some `using` I was missing (not sure which) and VS wasn't suggesting as a fix. But after copying your `using`s from your examples that worked! Thanks!
